import time
from typing import Dict, Any

class ReportExporter:
    @staticmethod
    def generate_markdown(data: Dict[str, Any]) -> str:
        """Convert intelligence data into a professional Markdown briefing."""
        target = data.get("target_topic", "Target")
        scout = data.get("scout_data", {})
        analyst = data.get("analyst_data", {})
        strategist = data.get("strategist_data", {})
        metrics = data.get("metrics", {})

        md = []
        md.append(f"# 🛰️ AGENTPULSE EXECUTIVE INTELLIGENCE RADAR: {target.upper()}")
        md.append(f"*Generated by Gemini Autonomous Agent Swarm | Timestamp: {time.strftime('%Y-%m-%d %H:%M:%S')}*\n")
        md.append("---\n")

        # Threat Header
        score = analyst.get("overall_threat_score", 0)
        level = analyst.get("threat_level", "UNKNOWN")
        md.append(f"## 🚨 EXECUTIVE THREAT ASSESSMENT: **{score}/100** ({level})")
        md.append(f"> **Executive Summary:** {strategist.get('executive_summary', 'N/A')}\n")

        # Radar Metrics
        radar = analyst.get("radar_scores", {})
        md.append("### 📊 Multidimensional Radar Scores")
        md.append(f"- **Innovation Speed:** `{radar.get('innovation_speed', 0)}/100`")
        md.append(f"- **Pricing Competitiveness:** `{radar.get('pricing_competitiveness', 0)}/100`")
        md.append(f"- **Feature Depth:** `{radar.get('feature_depth', 0)}/100`")
        md.append(f"- **Enterprise Readiness:** `{radar.get('enterprise_readiness', 0)}/100`")
        md.append(f"- **Community Traction:** `{radar.get('community_traction', 0)}/100`\n")

        # Scout Intel
        md.append("## 🔍 SCOUT INTELLIGENCE & MARKET MOVES")
        md.append(f"**Market Category:** {scout.get('market_category', 'Tech')}\n")
        md.append("### Recent Announcements & Feature Drops")
        for a in scout.get("recent_announcements", []):
            md.append(f"- **[{a.get('date', 'Recent')}] {a.get('headline', '')}** *(Impact: {a.get('impact', 'Medium')})*")
        md.append("")

        # Pricing & Sentiment
        pricing = scout.get("pricing_model", {})
        md.append("### Pricing & Tiering")
        md.append(f"- **Free Tier:** {pricing.get('free_tier', 'N/A')}")
        md.append(f"- **Pro Tier:** {pricing.get('pro_tier', 'N/A')}")
        md.append(f"- **Enterprise:** {pricing.get('enterprise', 'N/A')}\n")

        # SWOT
        swot = analyst.get("swot_analysis", {})
        md.append("## 🧭 STRATEGIC SWOT MATRIX")
        md.append("### 🟢 Strengths")
        for s in swot.get("strengths", []):
            md.append(f"- {s}")
        md.append("### 🔴 Weaknesses")
        for w in swot.get("weaknesses", []):
            md.append(f"- {w}")
        md.append("### 🟡 Opportunities")
        for o in swot.get("opportunities", []):
            md.append(f"- {o}")
        md.append("### 🟣 Threats")
        for t in swot.get("threats", []):
            md.append(f"- {t}")
        md.append("")

        # Comparison Matrix
        md.append("## ⚔️ CAPABILITY COMPARISON MATRIX")
        md.append("| Capability | Competitor Status | Market Benchmark | Threat Impact |")
        md.append("| :--- | :--- | :--- | :--- |")
        for row in analyst.get("comparison_matrix", []):
            md.append(f"| {row.get('capability', '')} | {row.get('competitor_status', '')} | {row.get('market_benchmark', '')} | {row.get('threat_impact', '')} |")
        md.append("")

        # Actionable Counter-Plays
        md.append("## 🎯 ACTIONABLE COUNTER-PLAYS & DEFENSE")
        for play in strategist.get("strategic_counter_plays", []):
            md.append(f"### 🛡️ {play.get('play_title', 'Counter-Play')} ({play.get('horizon', 'Immediate')})")
            md.append(f"- **Action Plan:** {play.get('action_plan', '')}")
            md.append(f"- **Expected Impact:** {play.get('expected_impact', 'High')}\n")

        # Telemetry
        md.append("## 📈 AGENT OBSERVABILITY & TELEMETRY")
        md.append(f"- **Total Multi-Agent Invocations:** {metrics.get('total_invocations', 3)}")
        md.append(f"- **Total Tokens Processed:** {metrics.get('total_tokens', 0)}")
        md.append(f"- **Total Swarm Latency:** {metrics.get('total_latency_ms', 0)} ms (Avg: {metrics.get('avg_latency_ms', 0)} ms/agent)")

        return "\n".join(md)

exporter = ReportExporter()
